input {
	kb_layout = us
	kb_options = caps:escape
	follow_mouse = 1
	sensitivity = 0
	touchpad {
		natural_scroll = true
	}
}

device {
	name = epic-mouse-v1
	sensitivity = -0.5
	accel_profile = flat
}
