browser {
    windowrule = tag +browser, match:class librewolf
    windowrule = tag +browser, match:class brave-browser
    windowrule = tag +browser, match:class brave-browser-beta
    windowrule = tag +browser, match:class brave-browser-nightly
    windowrule = tag +browser, match:class helium
    windowrule = tag +browser, match:class (?i).*(mullvad).*
    windowrule = workspace 2, opacity 2, match:tag browser
}

system {
    windowrule = tag +system, match:class (?i).*(easyeffects).*
    windowrule = tag +system, match:class (?i).*(easyeffects).*
    windowrule = tag +system, match:class (?i).*(opentabletdriver).*
    windowrule = workspace 5, match:tag system
}

float {
	windowrule = tag +float, match:class (?i).*(pavucontrol).*
	windowrule = tag +float, match:class btop
	windowrule = tag +float, match:class mail
	windowrule = float on, match:tag float
}

notes {
	windowrule = tag +notes, match:class (?i).*(rnote).*
    windowrule = workspace 1, opacity 2, match:tag notes
}

misc {
	windowrule = workspace special:work silent, match:class (?i).*(superproductivity).*
}
